### ISSUE TITLE
Improving Responsiveness of Project

### ISSUE THREAD

**Issue by Silent-Watcher** [Silent-Watcher/todoApp#1]
My project currently lacks responsiveness, making it difficult for users to access and interact with the application on various devices such as mobile phones, tablets, and different screen resolutions. While the project functions well on desktop screens, it fails to adapt gracefully to smaller screens, leading to usability challenges and a subpar experience for mobile users.

Additional context
Feel free to comment on this issue with your thoughts, ideas, or any code snippets you believe might assist in achieving responsiveness. Let's collaborate to create an inclusive, accessible, and user-friendly experience for all users, regardless of their device.

Thank you for your time and support. I look forward to working together on this important endeavor. 🤗😎
Leave a star before you leave ⭐

**Comment by DylanP97** [comment]
Hi there,
I can work on this
Let me know if this is still available and if I can be assign to this issue
